// vue/src/components/AddPeopleForm.vue
<template>
  <Form class="uk-form-stacked" @submit="onSubmit">

      <div class="uk-margin">
          <label class="uk-form-label" for="form-stacked-text">Name</label>
          <div class="uk-form-controls">
              <Field class="uk-input" name="name" type="text" placeholder="Some text..." :rules="nameRules"/>
              <ErrorMessage name="name"/>
          </div>
      </div>

      <div class="uk-margin">
          <label class="uk-form-label" for="form-stacked-text">Email</label>
          <div class="uk-form-controls">
              <Field class="uk-input" name="email" type="text" placeholder="Some text..." :rules="emailRules"/>
              <ErrorMessage name="email"/>
          </div>
      </div>

      <div class="uk-margin">
          <label class="uk-form-label" for="form-stacked-select">Select</label>
          <div class="uk-form-controls">
              <Field class="uk-select" as="select" name="countries" id="form-stacked-select" multiple uk-form-custom="target: true" :rules="countriesRules">
                  <option v-for="c in allCountries" :key="c.id" :value="c.id">{{ c.name.common }}</option>
              </Field>
              <ErrorMessage name="countries"/>
          </div>
      </div>

      <div class="uk-margin">
          <button class="uk-button uk-button-primary" href="#">Save</button>
      </div>


  </Form>
</template>

<script>
import { Field, Form, ErrorMessage } from 'vee-validate';
import * as yup from 'yup';
export default {
  components: {
    Field,
    Form,
    ErrorMessage,
  },
  name: "AddPeopleForm",
  inject: ["$http"],
  data() {
    return {
      nameRules: yup.string().required().min(5),
      emailRules: yup.string().required().email(),
      countriesRules: yup.array().required().min(1),
      allCountries: []
    };
  },
  mounted() {
    this.$http
        .get("http://localhost:3000/countries")
        .then((response) => (this.allCountries = response?.data));
  },
  methods: {
    onSubmit(values) {
      const that = this
      this.$http.post('http://localhost:3000/people', values)
        .then(function () {
          that.$emit('addedPeople')
        })
        .catch(function (error) {
          console.log(error);
        });
    },
  },
};
</script>

// angularjs/src/app/add-people-form/add-people-form.component.ts
import { HttpClient } from '@angular/common/http';
import { Component, EventEmitter, OnInit, Output } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';

@Component({
  selector: 'app-add-people-form',
  templateUrl: './add-people-form.component.html',
  styleUrls: ['./add-people-form.component.css']
})
export class AddPeopleFormComponent implements OnInit {
  @Output() event = new EventEmitter<string>();
  add_people_form: FormGroup
  countries: any
  constructor(private fb: FormBuilder, private http : HttpClient) {
    this.createForm();
  }

  ngOnInit(): void {
    this.http.get('http://localhost:3000/countries')
      .subscribe(Response => {

      if (Response) {
        this.countries = Response
      }
    });
  }

  createForm() {
    this.add_people_form = this.fb.group({
      name: [null, [Validators.required, Validators.minLength(5)]],
      email: [null, [Validators.required, Validators.email]],
      countries: [null, [Validators.required, Validators.minLength(1)]]
    });
  }

  onSubmit() {
    if(this.add_people_form.invalid) {
      return;
    } else {
      this.http.post('http://localhost:3000/people', this.add_people_form.value).subscribe(Response => {
        if (Response) {
          this.event.next('addedPoeple');
        }
      })
      return
    }
  }

}

<form class="uk-form-stacked" [formGroup]="add_people_form" (ngSubmit)="onSubmit()">

    <div class="uk-margin">
        <label class="uk-form-label" for="form-stacked-text">Name</label>
        <div class="uk-form-controls">
            <input class="form-control" class="uk-input" formControlName="name" name="name" type="text" placeholder="Some text...">
            <div *ngIf="add_people_form.controls['name'].invalid && (add_people_form.controls['name'].dirty || add_people_form.controls['name'].touched)" class="alert alert-danger">
                Name has errors
            </div>
        </div>
    </div>

    <div class="uk-margin">
        <label class="uk-form-label" for="form-stacked-text">Email</label>
        <div class="uk-form-controls">
            <input class="form-control" class="uk-input" formControlName="email"  name="email" type="text" placeholder="Some text...">
            <div *ngIf="add_people_form.controls['email'].invalid && (add_people_form.controls['email'].dirty || add_people_form.controls['email'].touched)" class="alert alert-danger">
                Email has errors
            </div>
        </div>
    </div>

    <div class="uk-margin">
        <label class="uk-form-label" for="form-stacked-select">Select</label>
        <div class="uk-form-controls">
            <select class="uk-select" formControlName="countries" multiple uk-form-custom="target: true" >
                <option *ngFor="let c of countries;" value="{{c.id}}">{{ c.name.common }}</option>
            </select>
            <div *ngIf="add_people_form.controls['countries'].invalid && (add_people_form.controls['countries'].dirty || add_people_form.controls['countries'].touched)" class="alert alert-danger">
                Countries has errors
            </div>
        </div>
    </div>

    <div class="uk-margin">
        <button class="uk-button uk-button-primary" href="#" type="submit">Save</button>
    </div>


</form>
