// angularjs/src/app/people/people.component.ts
import { Component, OnInit } from '@angular/core';
import {HttpClient} from '@angular/common/http';

@Component({
  selector: 'app-people',
  templateUrl: './people.component.html',
  styleUrls: ['./people.component.css']
})
export class PeopleComponent implements OnInit {
  people:any;

  constructor(private http : HttpClient){
  }

  ngOnInit(): void {
    this.getAllPoeple()
  }

  getAllPoeple(): void {
    this.http.get('http://localhost:3000/people')
    .subscribe(Response => {

      if (Response) {
        this.people = Response
      }
    });
  }

}

<h3>All people</h3>
<ul uk-accordion>
    <li>
        <a class="uk-accordion-title" href="#">Add</a>
        <div class="uk-accordion-content">
            <app-add-people-form (event)="getAllPoeple()"></app-add-people-form>
        </div>
    </li>
</ul>
<app-people-box *ngFor="let e of people;" [data]="e"></app-people-box>

// vue/src/views/People.vue
<template>
  <h3>All people</h3>
  <ul uk-accordion>
    <li>
        <a class="uk-accordion-title" href="#">Add</a>
        <div class="uk-accordion-content">
            <AddPeopleForm @addedPeople="getAll"/>
        </div>
    </li>
</ul>
  <PeopleBox v-for="p in people" :key="p.id" :data="p" />
</template>

<script>
import PeopleBox from "../components/PeopleBox.vue";
import AddPeopleForm from "../components/AddPeopleForm.vue";
export default {
  name: "People",
  inject: ["$http"],
  components: {
    PeopleBox,
    AddPeopleForm,
  },
  data() {
    return {
      people: null,
    };
  },
  mounted() {
    this.getAll()
  },

  methods: {
    getAll() {
      this.$http
        .get("http://localhost:3000/people")
        .then((response) => (this.people = response?.data));
    }
  }
};
</script>
